const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states=['وصلت إلى مخزن المنشأ','غادرت المخزن','وصلت إلى ليبيا','جاهزة للاستلام','تم التسليم'];
let state=null,setup=false;
async function api(path,method='GET',data){const r=await fetch('/api'+path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await r.json();if(!r.ok){if(r.status===401&&path!=='/login'){state=null;$('workspace').hidden=true;$('auth').hidden=false;$('identity').textContent='مرحبًا بك';$('list').innerHTML='';$('detail').close()}throw Error(result.error)}return result}
function notice(text){$('notice').textContent=text}
async function refresh(){state=await api('/state');$('auth').hidden=true;$('workspace').hidden=false;$('identity').textContent=state.user.name+' · '+state.user.code;$('greeting').textContent=state.user.role==='customer'?'شحناتك، خطوة بخطوة':state.user.role==='staff'?'مساحة الموظف':'لوحة الإدارة';$('manage-tab').hidden=state.user.role==='customer';currentCustomer.code=state.user.role==='customer'?state.user.code:state.users.find(c=>c.role==='customer'&&c.active)?.code||'';renderShipments();renderForms();renderAddresses()}
function tab(name){['ship','ware','manage'].forEach(id=>{$(id).hidden=id!==name;$(id+'-tab').classList.toggle('active',id===name)})}
function renderAddresses(){if(state.user.role==='customer')$('address-customer').innerHTML='';else{$('address-customer').innerHTML=`<label>عرض العنوان بكود الزبون <select id="address-code">${state.users.filter(c=>c.role==='customer'&&c.active).map(c=>`<option value="${esc(c.code)}">${esc(c.code)} · ${esc(c.name)}</option>`).join('')}</select></label>`;if($('address-code'))$('address-code').onchange=e=>{currentCustomer.code=e.target.value;renderWarehouses()}}if(currentCustomer.code)renderWarehouses();else $('warehouses').innerHTML='<article>أضف زبونًا لعرض العنوان بكوده.</article>'}
function photo(s){return s.hasPhoto?`<div class="shipment-photo"><img src="/api/shipments/${encodeURIComponent(s.id)}/photo?v=${Date.now()}" alt="صورة الشحنة ${esc(s.id)}" loading="lazy"></div>`:'<p class="muted">لم تُضف صورة بعد</p>'}
function renderShipments(){const q=$('search').value.trim().toUpperCase(),country=$('filter-country').value,mode=$('filter-mode').value;const rows=state.shipments.filter(s=>s.id.includes(q)&&(!country||s.country===country)&&(!mode||s.mode===mode));$('list').innerHTML='';rows.forEach(s=>{const card=document.createElement('article');card.innerHTML=`<div class="row"><span>${esc(s.country)} ← ليبيا · ${esc(s.mode)}</span><span class="badge">${esc(s.status)}</span></div><h3 dir="ltr" class="tracking-title">${esc(s.id)}</h3><p class="muted">${state.user.role!=='customer'?'الزبون: '+esc(s.customer)+' · ':''}${esc(s.weight)}</p>${photo(s)}<div class="progress"><span style="width:${s.step*25}%"></span></div><p>الوصول المتوقع: ${esc(s.date)}</p><button class="primary detail-button">تفاصيل الشحنة</button>${state.user.role!=='customer'?`<p><label>الحالة <select class="status">${states.map((x,i)=>`<option value="${i}" ${s.step===i?'selected':''}>${x}</option>`).join('')}</select></label></p><label class="photo-upload">${s.hasPhoto?'تغيير الصورة':'إضافة صورة'}<input class="photo-input" type="file" accept="image/jpeg,image/png,image/webp" aria-label="صورة الشحنة"></label>`:''}`;card.querySelector('.detail-button').onclick=()=>details(s);const sel=card.querySelector('.status');if(sel)sel.onchange=async()=>{try{await api('/shipments/'+s.id,'PATCH',{step:Number(sel.value)});await refresh();notice('تم تحديث حالة الشحنة.')}catch(e){sel.value=String(s.step);notice(e.message)}};const input=card.querySelector('.photo-input');if(input)input.onchange=()=>upload(s,input);$('list').appendChild(card)});if(!rows.length)$('list').innerHTML='<article>لا توجد شحنات تطابق الاختيار.</article>'}
function details(s){const d=$('detail');d.innerHTML=`<div class="row"><h2 dir="ltr">${esc(s.id)}</h2><button id="close-detail">إغلاق</button></div>${photo(s)}<p>${esc(s.weight)} · ${esc(s.mode)} · ${esc(s.country)}</p><p>الرحلة: ${esc(s.trip)}</p><ol>${states.map((x,i)=>`<li>${i<=s.step?'✓ ':''}${x}</li>`).join('')}</ol>`;$('close-detail').onclick=()=>d.close();d.showModal()}
async function upload(s,input){const file=input.files[0];if(!file)return;if(file.size>5*1024*1024){notice('اختر صورة أقل من 5 ميجابايت.');input.value='';return}input.disabled=true;try{const photo=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});await api('/shipments/'+s.id+'/photo','POST',{photo});await refresh();notice('تم حفظ الصورة.')}catch(e){notice(e.message||'تعذّر رفع الصورة.')}finally{input.disabled=false;input.value=''}}
function renderForms(){if(state.user.role==='customer'){$('forms').innerHTML='';$('users').innerHTML='';return}const customers=state.users.filter(c=>c.role==='customer'&&c.active);$('forms').innerHTML=`${state.user.role==='admin'?`<form id="user-form"><h3>إضافة حساب</h3><label>نوع الحساب<select name="role"><option value="customer">زبون</option><option value="staff">موظف</option></select></label><label>الاسم<input name="name" required maxlength="100" placeholder="اكتب اسم الزبون أو الموظف"></label><label>رقم الهاتف<input name="phone" type="tel" dir="ltr" required maxlength="25" placeholder="مثال: +218912345678" autocomplete="tel"></label><label>الكود<input name="code" placeholder="مثال: LN-1001" required pattern="[A-Za-z0-9-]{2,64}" dir="ltr" maxlength="64"></label><label>كلمة المرور<input name="password" type="password" required minlength="8" maxlength="128" autocomplete="new-password"></label><button class="primary">حفظ الحساب</button><p role="status"></p></form>`:''}<form id="shipment-form"><h3>إضافة شحنة</h3><label>الزبون<select name="customer" required>${customers.map(c=>`<option value="${esc(c.code)}">${esc(c.code)} · ${esc(c.name)}</option>`).join('')}</select></label><label>رقم التتبع<input name="id" placeholder="اكتب رقم تتبع الشحنة" required pattern="[A-Za-z0-9-]{2,64}" dir="ltr" maxlength="64"></label><label>الدولة<select name="country"><option>الصين</option><option>الإمارات</option><option>السعودية</option></select></label><label>نوع الشحن<select name="mode"><option>جوي</option><option>بحري</option></select></label><label>الوزن / الحجم<input type="number" name="weight" required min="0.01" max="100000" step="0.01"></label><label>الوحدة<select name="unit"><option>كجم</option><option>متر مكعب</option></select></label><label>رقم الرحلة<input name="trip" maxlength="64" placeholder="مثال: CN-A107"></label><label>الوصول المتوقع<input name="date" type="date"></label><label>صورة الشحنة (اختياري)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"><small>اختر صورة JPG أو PNG أو WebP، بحد أقصى 5 ميجابايت.</small></label><button class="primary" ${customers.length?'':'disabled'}>حفظ الشحنة</button><p role="status"></p></form>`;
if($('user-form'))$('user-form').onsubmit=e=>submitForm(e,'/users','تم إنشاء الحساب.');$('shipment-form').onsubmit=e=>submitForm(e,'/shipments','تمت إضافة الشحنة. أضف صورتها من تبويب الشحنات.');$('users').innerHTML='';$('users-title').hidden=state.user.role!=='admin';if(state.user.role==='admin')state.users.filter(c=>c.role!=='admin').forEach(c=>{const card=document.createElement('article');card.innerHTML=`<div class="row"><span>${esc(c.name)} · <b dir="ltr">${esc(c.code)}</b><br><small>${c.role==='staff'?'موظف':'زبون'} · ${c.active?'نشط':'موقوف'}</small><br><span dir="ltr">${esc(c.phone||'')}</span></span><div><button class="toggle">${c.active?'إيقاف':'تفعيل'}</button> <button class="reset">تغيير كلمة المرور</button></div></div>`;card.querySelector('.toggle').onclick=async()=>{try{await api('/users/'+c.code,'PATCH',{active:!c.active});await refresh();notice('تم تحديث الحساب.')}catch(e){notice(e.message)}};card.querySelector('.reset').onclick=()=>resetPassword(c);$('users').appendChild(card)})}
async function submitForm(e,path,success){e.preventDefault();const form=e.target,button=form.querySelector('button'),feedback=form.querySelector('[role=status]');button.disabled=true;let created=false;try{const data=Object.fromEntries(new FormData(form));const file=data.photo;delete data.photo;let imageData=null;if(file&&file.size){if(file.size>5*1024*1024)throw Error('اختر صورة أقل من 5 ميجابايت.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('اختر صورة JPG أو PNG أو WebP.');imageData=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('تعذّر قراءة الصورة.'));r.readAsDataURL(file)})}await api(path,'POST',data);created=true;if(imageData){try{await api('/shipments/'+encodeURIComponent(data.id.trim().toUpperCase())+'/photo','POST',{photo:imageData})}catch(error){form.reset();await refresh();tab('ship');notice('تم حفظ الشحنة، لكن الصورة لم تُحفظ: '+error.message+' يمكنك إضافتها من بطاقة الشحنة.');return}}form.reset();await refresh();if(path==='/shipments')tab('ship');notice(path==='/shipments'&&imageData?'تم حفظ الشحنة وصورتها.':success)}catch(err){if(created)notice('تم الحفظ، لكن تعذّر تحديث العرض. حدّث الصفحة.');else feedback.textContent=err.message}finally{button.disabled=false}}
function resetPassword(c){const d=$('detail');d.innerHTML=`<form class="live-form" id="password-form"><h2>تغيير كلمة المرور</h2><p dir="ltr">${esc(c.code)}</p><label>كلمة المرور الجديدة<input name="password" type="password" required minlength="8" maxlength="128" autocomplete="new-password"></label><p role="status"></p><button class="primary">حفظ</button><button type="button" id="cancel-password">إلغاء</button></form>`;$('cancel-password').onclick=()=>d.close();$('password-form').onsubmit=async e=>{e.preventDefault();try{await api('/users/'+c.code,'PATCH',Object.fromEntries(new FormData(e.target)));e.target.reset();d.close();notice('تم تغيير كلمة المرور وإنهاء جلسات الحساب السابقة.')}catch(err){e.target.querySelector('[role=status]').textContent=err.message}};d.showModal()}
$('auth-form').onsubmit=async e=>{e.preventDefault();$('auth-submit').disabled=true;try{const data=Object.fromEntries(new FormData(e.target));if(setup){await api('/setup','POST',data);setup=false;$('setup-key').hidden=true;$('setup-name').hidden=true;$('setup-name').querySelector('input').required=false;$('auth-title').textContent='تسجيل الدخول';$('auth-submit').textContent='دخول'}await api('/login','POST',data);e.target.reset();$('auth-message').textContent='';await refresh();tab('ship')}catch(err){$('auth-message').textContent=err.message}finally{$('auth-submit').disabled=false}};
$('logout').onclick=async()=>{try{await api('/logout','POST',{});location.reload()}catch(e){notice(e.message)}};
['ship','ware','manage'].forEach(name=>$(name+'-tab').onclick=()=>tab(name));['search','filter-country','filter-mode'].forEach(id=>$(id).oninput=renderShipments);
(async()=>{try{const b=await api('/bootstrap');setup=b.needsSetup;$('setup-key').hidden=!(setup&&b.requiresSetupKey);if(setup){$('auth-title').textContent='إنشاء حساب الإدارة لأول مرة';$('setup-name').hidden=false;$('setup-name').querySelector('input').required=true;$('auth-submit').textContent='إنشاء حساب الإدارة';return}try{await refresh()}catch(e){$('auth-message').textContent='أدخل كودك وكلمة المرور.'}}catch(e){$('auth-message').textContent=e.message}})();



if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
let installPrompt=null;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('install-app').hidden=false});
$('install-app').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('install-app').hidden=true};
window.addEventListener('appinstalled',()=>{$('install-app').hidden=true;installPrompt=null});
function renderTripControls(){const groups=[];state.shipments.forEach(s=>{if(s.trip==='لم تُحدد')return;const key=[s.trip,s.country,s.mode].join('|');let g=groups.find(x=>x.key===key);if(!g){g={key,trip:s.trip,country:s.country,mode:s.mode,count:0};groups.push(g)}g.count++});if(!groups.length)return;const box=document.createElement('form');box.id='trip-status-form';box.innerHTML=`<h3>تحديث رحلة كاملة</h3><p class="muted">غيّر حالة كل شحنات الرحلة لنفس الدولة ونوع الشحن دفعة واحدة.</p><label>الرحلة والدولة ونوع الشحن<select name="group">${groups.map((g,i)=>`<option value="${i}">${esc(g.trip)} · ${esc(g.country)} · ${esc(g.mode)} · ${g.count} شحنة</option>`).join('')}</select></label><label>الحالة الجديدة<select name="step">${states.map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select></label><p id="trip-count" class="muted"></p><button class="primary">تحديث الشحنات</button><p role="status"></p>`;$('forms').prepend(box);const updateCount=()=>{const g=groups[Number(box.group.value)];$('trip-count').textContent=`سيتم تحديث ${g.count} شحنة.`};box.group.onchange=updateCount;updateCount();box.onsubmit=async e=>{e.preventDefault();const g=groups[Number(box.group.value)],button=box.querySelector('button'),feedback=box.querySelector('[role=status]');button.disabled=true;try{const result=await api('/trips/status','PATCH',{trip:g.trip,country:g.country,mode:g.mode,step:Number(box.step.value)});await refresh();notice(`تم تحديث ${result.updatedCount} شحنة في الرحلة ${g.trip}.`)}catch(err){feedback.textContent=err.message}finally{button.disabled=false}}}
const existingRenderForms=renderForms;renderForms=function(){existingRenderForms();if(state.user.role!=='customer')renderTripControls()};
