import {searchShipments,tripKey,tripSummary,attentionReasons,guessColumns,importRows,reviewImport,csv,code,normalize} from './ops-core.mjs';
export const tabs=['trips','import','attention','alerts','billing','audit'];
const names={trips:'الرحلات',import:'استيراد Excel',attention:'تحتاج متابعة',alerts:'الإشعارات',billing:'الحسابات المالية',audit:'سجل التغييرات'};
const stages=['وصلت إلى مخزن المنشأ','غادرت المخزن','وصلت إلى ليبيا','جاهزة للاستلام','تم التسليم'];
const $=id=>document.getElementById(id);let app,selectedTrip='',selected=new Set(),scanSeen=new Set();
const get=()=>app.getState(),e=v=>app.esc(v),num=v=>Number(v||0).toLocaleString('ar-LY',{maximumFractionDigits:3});
const canManage=()=>['admin','staff','warehouse'].includes(get()?.user.role);
const option=(value,label,current)=>`<option value="${e(value)}" ${value===current?'selected':''}>${e(label)}</option>`;
function download(name,value,type='text/csv;charset=utf-8'){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function fillOptions(el,html){const old=el.value;el.innerHTML=html;if([...el.options].some(o=>o.value===old))el.value=old;}
export function init(context){
 app=context;const css=document.createElement('link');css.rel='stylesheet';css.href='/operations.css';document.head.append(css);
 const nav=document.querySelector('#workspace nav');tabs.forEach(id=>{const b=document.createElement('button');b.id=id+'-tab';b.textContent=names[id];b.onclick=()=>app.tab(id);nav.append(b);const s=document.createElement('section');s.id=id;s.hidden=true;$('workspace').append(s)});
 $('search').placeholder='رقم التتبع، كود الزبون، الاسم أو الهاتف';$('search').setAttribute('aria-label','بحث شامل بالشحنات والزبائن');
 const filters=document.querySelector('#ship .filters');filters.insertAdjacentHTML('beforeend','<select id="filter-trip" aria-label="فلترة الرحلة"></select><select id="filter-step" aria-label="فلترة الحالة"><option value="">كل الحالات</option>'+stages.map((s,i)=>option(String(i),s,'')).join('')+'</select><button id="clear-filters" type="button">مسح الفلاتر</button><button id="scan-search" type="button">مسح باركود</button>');
 $('filter-trip').onchange=$('filter-step').onchange=app.renderShipments;$('clear-filters').onclick=()=>{['search','filter-country','filter-mode','filter-trip','filter-step'].forEach(id=>$(id).value='');app.renderShipments()};$('scan-search').onclick=()=>openScanner();
 const summary=document.createElement('p');summary.id='result-count';summary.setAttribute('role','status');$('list').before(summary);
 $('trips').innerHTML='<div class="ops-heading"><div><h2>الرحلات</h2><p class="muted">كشف واحد لكل رحلة، من التجهيز إلى الاستلام.</p></div><label>اختَر الرحلة<select id="trip-picker"></select></label></div><div id="trip-view"></div>';
 $('trip-picker').onchange=()=>{selectedTrip=$('trip-picker').value;selected.clear();scanSeen.clear();renderTrip()};
 mountImport();
}
export function filter(state){const result=searchShipments(state.shipments,state.users,{query:$('search').value,country:$('filter-country').value,mode:$('filter-mode').value,trip:$('filter-trip')?.value,step:$('filter-step')?.value});if($('result-count'))$('result-count').textContent=`${num(result.length)} شحنة من ${num(state.shipments.length)}`;return result;}
export function sync(){
 if(!get())return;const s=get(),customer=s.user.role==='customer';
 tabs.forEach(id=>{$(id+'-tab').hidden=customer?!['alerts','billing'].includes(id):(id==='audit'?s.user.role!=='admin':id==='import'?!canManage():id==='billing'?!['admin','accountant'].includes(s.user.role):false);if($(id+'-tab').hidden&&!$(id).hidden)app.tab('ship')});
 fillOptions($('filter-trip'),option('','كل الرحلات','')+[...new Map(s.shipments.map(t=>[tripKey(t),t])).values()].map(t=>option(tripKey(t),`${t.trip} · ${t.country} · ${t.mode}`,'')).join(''));
 fillOptions($('trip-picker'),s.trips.map(t=>option(tripKey(t),`${t.code} · ${t.country} · ${t.mode}`,selectedTrip)).join(''));selectedTrip=$('trip-picker').value;
 renderTrip();renderAttention();syncImportOptions();
 if(!$('alerts').hidden)renderAlerts();if(!$('billing').hidden)renderBilling();if(!$('audit').hidden)renderAudit();
}
export function opened(name){if(!get())return;if(name==='alerts')renderAlerts();if(name==='billing')renderBilling();if(name==='audit')renderAudit();}
export function enhanceForms(){
 if(!get())return;const roles={staff:'موظف مسؤول',warehouse:'موظف مخزن',accountant:'محاسب'};
 const role=$('user-form')?.elements.role;if(role&&!role.querySelector('[value=warehouse]')){role.insertAdjacentHTML('beforeend',option('warehouse','موظف مخزن','')+option('accountant','محاسب',''))}
 ['shipment-form','edit-shipment-form'].forEach(id=>{const f=$(id);if(!f||f.elements.category)return;const old=id==='edit-shipment-form'?get().shipments.find(s=>s.id===f.elements.id.value):null;const label=document.createElement('label');label.textContent='تصنيف الشحنة (للتسعير)';const input=document.createElement('input');input.name='category';input.maxLength=80;input.required=true;input.value=old?.category||'عام';input.setAttribute('list','category-options');label.append(input);f.querySelector('.primary').before(label)});
 if(!$('category-options')){const d=document.createElement('datalist');d.id='category-options';document.body.append(d)}$('category-options').innerHTML=[...new Set(['عام',...get().shipments.map(s=>s.category||'عام')])].map(c=>option(c,c,'')).join('');
 if(get().user.role==='accountant'){$('forms').innerHTML='';$('users').innerHTML='';$('users-title').hidden=true}
 $('list').querySelectorAll('.status,.edit-button,.photo-upload,.delete-button').forEach(el=>{if(!canManage())el.hidden=true;if(el.classList.contains('delete-button')&&get().user.role==='warehouse')el.hidden=true});
 if(get().user.role==='admin')$('users').querySelectorAll('article').forEach(card=>{const c=get().users.find(u=>u.code===card.querySelector('b')?.textContent);if(!c||!roles[c.role]||card.querySelector('.role-edit'))return;const button=document.createElement('button');button.className='role-edit';button.textContent='صلاحية: '+roles[c.role];button.onclick=()=>{const d=$('detail');d.innerHTML=`<form class="live-form"><h2>صلاحية ${e(c.name)}</h2><label>الدور<select name="role">${Object.entries(roles).map(([v,l])=>option(v,l,c.role)).join('')}</select></label><p class="muted">المخزن: الشحنات دون حذف أو حسابات. المحاسب: الفواتير والمدفوعات دون تعديل الشحنات. الموظف المسؤول: إدارة الشحنات وحذفها دون الحسابات المالية.</p><p role="status"></p><button class="primary">حفظ الصلاحية</button><button type="button" id="role-close">إلغاء</button></form>`;d.querySelector('#role-close').onclick=()=>d.close();d.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('.primary');b.disabled=true;try{await app.api('/users/'+encodeURIComponent(c.code),'PATCH',{role:ev.target.elements.role.value});d.close();await app.refresh();app.notice('تم تحديث الصلاحية وإنهاء جلسات الموظف السابقة.')}catch(err){ev.target.querySelector('[role=status]').textContent=err.message;b.disabled=false}};d.showModal()};card.querySelector('.row').append(button)});
}
function currentTrip(){return get().trips.find(t=>tripKey(t)===selectedTrip)}
function currentRows(){return get().shipments.filter(s=>tripKey(s)===selectedTrip)}
function stat(label,value){return `<div class="stat"><span>${e(label)}</span><strong>${e(value)}</strong></div>`}
function rowsTable(rows,{selectable=false}={}){const users=new Map(get().users.map(u=>[u.code,u]));return `<div class="table-wrap" tabindex="0" role="region" aria-label="جدول الشحنات"><table><thead><tr>${selectable?'<th><input type="checkbox" id="select-all" aria-label="تحديد كل النتائج"></th>':''}<th>رقم التتبع</th><th>الزبون</th><th>الوزن / الحجم</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>${rows.map(s=>`<tr>${selectable?`<td><input type="checkbox" data-select="${e(s.id)}" aria-label="تحديد ${e(s.id)}" ${selected.has(s.id)?'checked':''}></td>`:''}<td dir="ltr">${e(s.id)}</td><td><b dir="ltr">${e(s.customer)}</b><br><small>${e(users.get(s.customer)?.name||'')}</small></td><td>${e(s.weight)}</td><td>${e(s.status)}</td><td><button data-detail="${e(s.id)}">تفاصيل</button>${canManage()?` <button data-edit="${e(s.id)}">تعديل</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">لا توجد شحنات مطابقة.</td></tr>'}</tbody></table></div>`}
function wireTable(root,rows){root.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>app.details(rows.find(s=>s.id===b.dataset.detail)));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{app.openEditShipment(rows.find(s=>s.id===b.dataset.edit));enhanceForms()});root.querySelectorAll('[data-select]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.select):selected.delete(c.dataset.select);updateSelected()});const all=root.querySelector('#select-all');if(all){all.checked=rows.length>0&&rows.every(s=>selected.has(s.id));all.indeterminate=rows.some(s=>selected.has(s.id))&&!all.checked;all.onchange=()=>{rows.forEach(s=>all.checked?selected.add(s.id):selected.delete(s.id));renderTripTable()}}}
function updateSelected(){if($('selected-count'))$('selected-count').textContent=`${num(selected.size)} شحنة محددة`;if($('bulk-transfer'))$('bulk-transfer').disabled=!selected.size;if($('bulk-status'))$('bulk-status').disabled=!selected.size;}
function renderTrip(){
 const t=currentTrip();if(!t){$('trip-view').innerHTML='<article>لا توجد رحلات بعد. أضف رحلة من الإدارة.</article>';return;}const rows=currentRows(),s=tripSummary(rows);selected=new Set([...selected].filter(id=>rows.some(r=>r.id===id)));
 const previous=$('trip-search')?.value||'';
 $('trip-view').innerHTML=`<div class="stats ops-stats">${stat('الشحنات',num(s.count))}${stat('الزبائن',num(s.customers))}${stat('الوزن — كجم',num(s.kg))}${s.m3?stat('الحجم — م³',num(s.m3)):''}</div><article class="trip-meta"><div><h3>رحلة ${e(t.code)}</h3><p>${e(t.country)} · ${e(t.mode)} · الوصول المتوقع ${e(t.date)}</p></div><div class="ops-actions"><button id="manifest-csv">تنزيل الكشف CSV</button><button id="manifest-print">طباعة الكشف</button>${canManage()?'<button id="scan-trip">مطابقة التفريغ بالباركود</button>':''}</div></article><div class="status-strip">${stages.map((x,i)=>`<span>${e(x)} <b>${num(s.states[i])}</b></span>`).join('')}</div><div class="filters"><input id="trip-search" aria-label="بحث داخل الرحلة" placeholder="ابحث داخل هذه الرحلة" value="${e(previous)}">${canManage()?'<span id="selected-count"></span><button id="bulk-transfer">نقل المحدد</button><button id="bulk-status">تغيير حالة المحدد</button>':''}</div><div id="trip-table"></div><div id="reconcile-summary"></div>`;
 $('trip-search').oninput=renderTripTable;$('manifest-csv').onclick=()=>download(`trip-${t.code}.csv`,csv([['رقم التتبع','الكود','الاسم','الوزن','الوحدة','الحالة','الوصول المتوقع'],...currentRows().map(r=>[r.id,r.customer,get().users.find(u=>u.code===r.customer)?.name,r.weightValue,r.unit,r.status,r.date])]));
 $('manifest-print').onclick=()=>{document.body.classList.add('printing-trip');window.print();document.body.classList.remove('printing-trip')};
 if(canManage()){$('bulk-transfer').onclick=()=>openBulk('transfer');$('bulk-status').onclick=()=>openBulk('status');$('scan-trip').onclick=()=>openScanner(true)}renderTripTable();loadReconciliations(t);
}
function renderTripTable(){const rows=searchShipments(currentRows(),get().users,{query:$('trip-search').value});$('trip-table').innerHTML=rowsTable(rows,{selectable:canManage()});wireTable($('trip-table'),rows);updateSelected();}
function openBulk(kind){const d=$('detail'),rows=currentRows().filter(r=>selected.has(r.id)),transfer=kind==='transfer';d.innerHTML=`<form class="live-form" id="bulk-form"><div class="row"><h2>${transfer?'نقل الشحنات المحددة':'تغيير الحالة'}</h2><button type="button" id="bulk-close">إغلاق</button></div><p>عدد الشحنات: ${num(rows.length)}. ${transfer?'الصور والحالة تبقى محفوظة.':''}</p>${transfer?`<label>الرحلة الجديدة<select name="target" required>${get().trips.filter(t=>t.step===0&&tripKey(t)!==selectedTrip).map(t=>option(tripKey(t),`${t.code} · ${t.country} · ${t.mode}`,'')).join('')}</select></label>`:`<label>الحالة<select name="step">${stages.map((s,i)=>option(String(i),s,'')).join('')}</select></label>`}<p role="status"></p><button class="primary">تأكيد ${transfer?'النقل':'التحديث'}</button></form>`;
 d.querySelector('#bulk-close').onclick=()=>d.close();d.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const f=ev.target,b=f.querySelector('.primary');b.disabled=true;try{const target=transfer?JSON.parse(f.elements.target.value):null;await app.api('/shipments/bulk','POST',{kind,ids:rows.map(r=>({id:r.id,updatedAt:r.updatedAt})),...(transfer?{trip:target[0],country:target[1],mode:target[2]}:{step:Number(f.elements.step.value)})});d.close();selected.clear();await app.refresh();app.notice('تم تحديث الشحنات المحددة وحفظ سجل التغيير.')}catch(err){f.querySelector('[role=status]').textContent=err.message}finally{b.disabled=false}};d.showModal();}
function renderAttention(){const rows=get().shipments.filter(s=>attentionReasons(s).length);$('attention').innerHTML=`<h2>تحتاج متابعة</h2><p class="muted">تأخر الوصول، نقص البيانات، أو مرور 7 أيام دون تغيير. ${num(rows.length)} شحنة.</p>${rows.length?rows.map(s=>`<article class="attention-row"><div><b dir="ltr">${e(s.id)}</b><p>${attentionReasons(s).map(e).join(' · ')} · ${e(s.customer)} · رحلة ${e(s.trip)}</p></div><button data-detail="${e(s.id)}">عرض الشحنة</button></article>`).join(''):'<article>لا توجد شحنات تحتاج متابعة حاليًا.</article>'}`;wireTable($('attention'),rows);}
// Feature surfaces are initialized below; all writes go through the authenticated API.
let importBook=null,importGrid=[],importData=[],importMapping={},importActions={},importExcluded=new Set(),importReview=[],importBusy=false;
function mountImport(){
 $('import').innerHTML=`<div class="ops-heading"><div><h2>استيراد كشف الشحنات</h2><p class="muted">ارفع الملف، راجع الأكواد والتكرار، ثم احفظ الدفعة مرة واحدة.</p></div><button id="import-template">تنزيل نموذج CSV</button></div><p class="ops-note">تُقرأ بيانات الملف داخل جهازك. لا يُنفّذ أي محتوى أو تعليمات مكتوبة فيه. الأكواد الناقصة <b dir="ltr">LN-</b> تُستبعد، وتحويل الأكواد يسري على هذه الدفعة فقط.</p><div class="ops-panel"><div class="ops-grid"><label>ملف Excel أو CSV<input id="import-file" type="file" accept=".xlsx,.xls,.csv"></label><label>الرحلة<select id="import-trip"></select></label><label>الوحدة<select id="import-unit"><option>كجم</option><option>متر مكعب</option></select></label></div><p id="import-message" role="status"></p></div><div id="import-columns" class="ops-panel" hidden></div><div id="import-mapping" class="ops-panel" hidden></div><div id="import-review"></div>`;
 $('import-template').onclick=()=>download('shipment-template.csv',csv([['رقم التتبع','كود الزبون','الوزن (كجم)','تصنيف الشحنة'],['EXAMPLE001','LN-0001','0.50','عام']]));
 $('import-file').onchange=readImportFile;$('import-trip').onchange=()=>{const t=get().trips.find(t=>tripKey(t)===$('import-trip').value);$('import-unit').value=t?.mode==='بحري'?'متر مكعب':'كجم';renderImportReview()};$('import-unit').onchange=renderImportReview;
}
function syncImportOptions(){fillOptions($('import-trip'),option('','اختَر رحلة محفوظة','')+get().trips.map(t=>option(tripKey(t),`${t.code} · ${t.country} · ${t.mode}${t.step>0?' · غادرت':''}`,'')).join(''));if(importData.length){renderImportMapping();renderImportReview()}}
async function readImportFile(){
 const file=$('import-file').files[0];if(!file)return;if(importBusy)return;importBook=null;importData=[];importMapping={};importActions={};importExcluded=new Set();$('import-review').innerHTML='';$('import-columns').hidden=true;$('import-mapping').hidden=true;
 if(file.size>10*1024*1024){$('import-message').textContent='الحد الأقصى للملف 10 ميجابايت.';return;}
 $('import-message').textContent='جاري قراءة الملف محليًا…';$('import-file').disabled=true;
 try{const bytes=await file.arrayBuffer();const result=await new Promise((resolve,reject)=>{const w=new Worker('/import-worker.js');const timer=setTimeout(()=>{w.terminate();reject(Error('استغرقت قراءة الملف وقتًا طويلًا. استخدم كشفًا أصغر.'))},20000);w.onmessage=ev=>{clearTimeout(timer);w.terminate();ev.data.error?reject(Error(ev.data.error)):resolve(ev.data)};w.onerror=()=>{clearTimeout(timer);w.terminate();reject(Error('تعذّر تحميل قارئ Excel. حدّث الصفحة.'))};w.postMessage(bytes,[bytes])});importBook=result.sheets;if(!importBook.length)throw Error('لا توجد أوراق عمل.');mountColumns(0);$('import-message').textContent=`تمت قراءة ${file.name}. راجع ورقة العمل والأعمدة قبل المتابعة.`;}catch(err){$('import-message').textContent=err.message}finally{$('import-file').disabled=false}
}
function mountColumns(sheetIndex){
 importGrid=importBook[sheetIndex].rows;const guessed=guessColumns(importGrid),width=Math.max(0,...importGrid.slice(0,30).map(r=>r.length));$('import-columns').hidden=false;
 const colOptions=(selected,optional=false)=>(optional?option('-1','بدون تصنيف',String(selected)):'')+Array.from({length:width},(_,i)=>option(String(i),`${i+1} — ${importGrid[guessed.header]?.[i]||'عمود'}`,String(selected))).join('');
 $('import-columns').innerHTML=`<h3>1. مطابقة الأعمدة</h3><div class="ops-grid"><label>ورقة العمل<select id="import-sheet">${importBook.map((s,i)=>option(String(i),s.name,String(sheetIndex))).join('')}</select></label><label>صف العناوين<input id="import-header" type="number" min="1" max="30" value="${guessed.header+1}"></label><label>رقم التتبع<select id="import-id">${colOptions(guessed.id)}</select></label><label>كود الزبون<select id="import-customer">${colOptions(guessed.customer)}</select></label><label>الوزن / الحجم<select id="import-weight">${colOptions(guessed.weight)}</select></label><label>التصنيف<select id="import-category">${colOptions(guessed.category,true)}</select></label></div><div class="review-actions"><button id="import-prepare" class="primary">قراءة الصفوف ومراجعتها</button><span id="column-error" role="status"></span></div>`;
 $('import-sheet').onchange=()=>{importData=[];$('import-review').innerHTML='';$('import-mapping').hidden=true;mountColumns(Number($('import-sheet').value))};$('import-prepare').onclick=()=>{try{const columns={header:Number($('import-header').value)-1,...Object.fromEntries(['id','customer','weight','category'].map(k=>[k,Number($('import-'+k).value)]))};if(columns.header<0||columns.header>=importGrid.length)throw Error('صف العناوين غير صالح.');importData=importRows(importGrid,columns);if(importData.length>1000)throw Error('الحد الأقصى 1000 شحنة في الدفعة. قسّم الملف.');if(!importData.length)throw Error('لم نجد صفوف شحنات في الأعمدة المحددة.');importActions={};importExcluded=new Set();$('column-error').textContent='';renderImportMapping();renderImportReview()}catch(err){importData=[];$('column-error').textContent=err.message;$('import-review').innerHTML=''}};
}
function renderImportMapping(){
 $('import-mapping').hidden=!importData.length;if(!importData.length)return;const customers=get().users.filter(u=>u.role==='customer'&&u.active),codes=[...new Set(importData.map(r=>r.originalCustomer))].filter(c=>c!=='LN-');
 $('import-mapping').innerHTML=`<h3>2. تحويل الأكواد لهذه الدفعة فقط</h3><p class="muted">اترك «كما في الملف» للكود الصحيح. الكود غير الموجود يحتاج اختيار حساب موجود أو إنشاء الحساب من الإدارة.</p><div class="ops-grid">${codes.map((c,i)=>`<label><span dir="ltr">${e(c||'(فارغ)')}</span><select data-map="${i}" aria-label="تحويل الكود ${e(c)}">${option('','كما في الملف',importMapping[c]||'')}${customers.map(u=>option(u.code,`${u.code} · ${u.name}`,importMapping[c])).join('')}</select></label>`).join('')}</div>`;
 $('import-mapping').querySelectorAll('[data-map]').forEach(el=>el.onchange=()=>{const c=codes[Number(el.dataset.map)];if(el.value)importMapping[c]=el.value;else delete importMapping[c];renderImportReview()});
}
function renderImportReview(){
 if(!importData.length)return;const t=get().trips.find(t=>tripKey(t)===$('import-trip').value);importReview=reviewImport(importData,get().users,get().shipments,{mapping:importMapping,trip:t,actions:importActions,excluded:importExcluded,unit:$('import-unit').value});const accepted=importReview.filter(r=>!r.skip),errors=accepted.filter(r=>r.errors.length),ready=accepted.filter(r=>!r.errors.length),skipped=importReview.filter(r=>r.skip);const sum=ready.reduce((v,r)=>v+r.weight,0);
 $('import-review').innerHTML=`<h3>3. مراجعة الدفعة</h3><p class="ops-note">${num(ready.filter(r=>r.action==='create').length)} جديدة · ${num(ready.filter(r=>r.action==='update').length)} تحديث/نقل · ${num(skipped.length)} مستبعدة · ${num(errors.length)} تحتاج تصحيحًا. إجمالي الجاهز: ${num(sum)} ${e($('import-unit').value)}</p><div class="table-wrap" tabindex="0" role="region" aria-label="مراجعة ملف الاستيراد"><table><thead><tr><th>استبعاد</th><th>صف</th><th>التتبع</th><th>الكود الأصلي ← النهائي</th><th>الوزن</th><th>الموجود حاليًا</th><th>القرار</th></tr></thead><tbody>${importReview.map(r=>`<tr class="${r.skip?'review-skip':''}"><td><input type="checkbox" data-exclude="${r.row}" aria-label="استبعاد الصف ${r.row}" ${r.skip?'checked':''} ${r.originalCustomer==='LN-'?'disabled':''}></td><td>${r.row}</td><td dir="ltr">${e(r.id)}</td><td><span dir="ltr">${e(r.originalCustomer)} → ${e(r.customer)}</span></td><td><input type="number" data-weight="${r.row}" value="${Number.isFinite(r.weight)?r.weight:''}" step="0.001" min="0.001" max="100000" aria-label="وزن الصف ${r.row}" style="width:110px;min-width:110px"></td><td>${r.old?`رحلة ${e(r.old.trip)} · ${e(r.old.country)} · ${e(r.old.mode)}<br><span dir="ltr">${e(r.old.customer)}</span> · ${e(r.old.weight)}`:'—'}</td><td>${r.old?`<select data-action="${r.row}" aria-label="قرار الصف ${r.row}">${option('review','اختر القرار',importActions[r.row]||'review')}${option('skip','تجاهل الموجود',importActions[r.row])}${option('update','تحديث ونقل إلى المختارة',importActions[r.row])}</select>`:''}<div class="${r.errors.length?'review-errors':'review-ok'}">${r.skip?'مستبعد':r.errors.length?r.errors.map(e).join('<br>'):r.action==='create'?'جاهزة للإضافة':'جاهزة للتحديث والنقل'}</div></td></tr>`).join('')}</tbody></table></div><div class="review-actions"><label class="ops-check"><input id="import-confirm" type="checkbox" ${errors.length||!ready.length?'disabled':''}>راجعت الأكواد والأوزان وقرارات نقل الموجود</label><button id="import-save" class="primary" disabled>حفظ ${num(ready.length)} شحنة</button><button id="review-download">تنزيل تقرير المراجعة</button></div><p id="import-save-message" role="status"></p>`;
 $('import-review').querySelectorAll('[data-exclude]').forEach(el=>el.onchange=()=>{const row=Number(el.dataset.exclude);if(el.checked)importExcluded.add(row);else{importExcluded.delete(row);if(importActions[row]==='skip')delete importActions[row]}renderImportReview()});
 $('import-review').querySelectorAll('[data-action]').forEach(el=>el.onchange=()=>{importActions[el.dataset.action]=el.value;importExcluded.delete(Number(el.dataset.action));renderImportReview()});
 $('import-review').querySelectorAll('[data-weight]').forEach(el=>el.onchange=()=>{importData.find(r=>r.row===Number(el.dataset.weight)).weight=Number(el.value);renderImportReview()});
 $('import-confirm').onchange=()=>{$('import-save').disabled=!$('import-confirm').checked||!!errors.length||!ready.length||importBusy};$('review-download').onclick=()=>download('import-review.csv',csv([['الصف','التتبع','الكود الأصلي','الكود النهائي','الوزن','القرار','الملاحظات'],...importReview.map(r=>[r.row,r.id,r.originalCustomer,r.customer,r.weight,r.action,r.errors.join('؛ ')])]));$('import-save').onclick=commitImport;
}
async function commitImport(){
 if(importBusy||!$('import-confirm').checked)return;const ready=importReview.filter(r=>!r.skip);if(!ready.length||ready.some(r=>r.errors.length))return;const t=get().trips.find(t=>tripKey(t)===$('import-trip').value);if(!t)return;
 importBusy=true;const controls=[...$('import').querySelectorAll('input,select,button')];controls.forEach(c=>c.disabled=true);$('import-save-message').textContent='جاري حفظ الدفعة. لا تغلق الصفحة…';
 try{const result=await app.api('/shipments/import','POST',{trip:t.code,country:t.country,mode:t.mode,rows:ready.map(r=>({id:r.id,customer:r.customer,weight:r.weight,unit:r.unit,category:r.category||'عام',action:r.action,updatedAt:r.old?.updatedAt||null}))});importData=[];importBook=null;$('import-file').value='';$('import-columns').hidden=true;$('import-mapping').hidden=true;$('import-review').innerHTML=`<article class="ops-note">تم حفظ ${num(result.created)} شحنة جديدة وتحديث ${num(result.updated)} شحنة. رقم الدفعة: <span dir="ltr">${e(result.batchId)}</span></article>`;await app.refresh();app.notice('تم حفظ الدفعة بالكامل. لن تؤدي إعادة رفع نفس الكشف إلى إضافة شحنات مكررة.')}catch(err){$('import-save-message').textContent=err.message+' لم نعد إرسال الطلب تلقائيًا؛ حدّث البيانات وراجع الدفعة قبل المحاولة.';}finally{importBusy=false;controls.forEach(c=>{if(c.isConnected)c.disabled=false});if($('import-confirm')){$('import-confirm').checked=false;$('import-save').disabled=true}}
}
async function renderAlerts(){
 $('alerts').innerHTML='<h2>الإشعارات</h2><p role="status">جاري التحميل…</p>';try{const rows=await app.api('/notifications'),customer=get().user.role==='customer';
 const wa={not_connected:'لم يُرسل واتساب (الربط أو الموافقة غير مفعّلين)',pending:'بانتظار إرسال واتساب',sending:'جاري إرسال واتساب',sent:'قُبل من واتساب للإرسال',delivered:'تم التسليم عبر واتساب',read:'قُرئ عبر واتساب',failed:'تعذّر إرسال واتساب',unknown:'نتيجة الإرسال غير مؤكدة؛ تحتاج مراجعة'};
 $('alerts').innerHTML=`<div class="ops-heading"><div><h2>الإشعارات</h2><p class="muted">إشعار مجمّع لكل زبون ورحلة ومرحلة. آخر 200 إشعار.</p></div><button id="alerts-refresh">تحديث</button></div>${customer?`<div class="ops-panel"><label class="ops-check"><input type="checkbox" id="whatsapp-consent" ${get().user.whatsappOptIn?'checked':''}>أوافق على استلام تحديثات شحناتي عبر واتساب على رقم حسابي</label><p class="muted">يمكنك إلغاء الموافقة في أي وقت. يبدأ الإرسال فقط بعد تفعيل خدمة الشركة.</p></div>`:get().user.role==='admin'?'<div id="whatsapp-connection" class="ops-panel"></div>':''}<div>${rows.map(n=>`<article class="attention-row"><div><b>رحلة ${e(n.trip)} · ${e(stages[n.step])}</b><p>${num(n.shipment_count)} شحنة · <span dir="ltr">${e(n.customer_code)}</span> · ${e(n.country)} · ${e(n.mode)}</p><small>${e(new Date(n.updated_at).toLocaleString('ar-LY'))} · ${e(wa[n.whatsapp_status]||n.whatsapp_status)}</small></div>${customer&&!n.read_at?`<button data-read="${e(n.id)}">تمت القراءة</button>`:`<span class="muted">${n.read_at?'مقروء لدى الزبون':'لم يقرأه الزبون بعد'}</span>`}</article>`).join('')||'<article>لا توجد إشعارات بعد. تظهر تلقائيًا عند تغيّر حالة الشحنات.</article>'}</div>`;
 $('alerts-refresh').onclick=renderAlerts;$('alerts').querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await app.api('/notifications/read','POST',{id:b.dataset.read});await renderAlerts()}catch(err){app.notice(err.message);b.disabled=false}});
 if(customer)$('whatsapp-consent').onchange=async ev=>{const el=ev.target;el.disabled=true;try{await app.api('/notifications/consent','POST',{enabled:el.checked});get().user.whatsappOptIn=el.checked;app.notice(el.checked?'تم حفظ موافقتك على إشعارات واتساب.':'تم إلغاء موافقة واتساب.')}catch(err){el.checked=!el.checked;app.notice(err.message)}finally{el.disabled=false}};
 if($('whatsapp-connection')){const c=await app.api('/whatsapp/status');$('whatsapp-connection').innerHTML=`<h3>واتساب الشركة <span dir="ltr">${e(c.sender)}</span></h3><p>${c.configured&&c.enabled?'الربط مفعّل. الإرسال للزبائن الموافقين فقط.':'الربط غير مفعّل بعد. يلزم اعتماد الرقم وقالب الرسالة في Meta، وإعداد مفاتيح الربط الآمنة وجدولة الإرسال.'}</p><p class="muted">الإشعارات داخل التطبيق تعمل مستقلّة عن واتساب. لا تُدخل مفاتيح الربط في هذه الصفحة أو في ملفات الواجهة.</p>`}
 }catch(err){$('alerts').innerHTML=`<h2>الإشعارات</h2><p class="ops-error" role="status">${e(err.message)}</p><button id="alerts-retry">إعادة المحاولة</button>`;$('alerts-retry').onclick=renderAlerts;}
}
let billingData=null,billingCustomer='',billingTrip='';
const money=(n,c)=>`${Number(n||0).toLocaleString('ar-LY',{minimumFractionDigits:2,maximumFractionDigits:2})} ${c}`;
async function renderBilling(){
 const root=$('billing');root.innerHTML='<h2>الحسابات المالية</h2><p role="status">جاري التحميل…</p>';try{billingData=await app.api('/billing');const customer=get().user.role==='customer',customers=get().users.filter(u=>u.role==='customer');
 if(customer)billingCustomer=get().user.code;if(!billingCustomer||!customers.some(u=>u.code===billingCustomer))billingCustomer=customers[0]?.code||'';
 root.innerHTML=`<div class="ops-heading"><div><h2>الحسابات المالية</h2><p class="muted">أسعار معتمدة، فواتير محفوظة، ومدفوعات مسجلة. لا توجد أسعار افتراضية.</p></div><button id="billing-refresh">تحديث</button></div>${customer?'':`<details class="ops-panel"><summary>إعداد أسعار الشحن (${num(billingData.rates.length)})</summary><div id="rates-list"></div><form id="rate-form" class="live-form"><div class="ops-grid"><label>الدولة<select name="country"><option>الصين</option><option>الإمارات</option><option>السعودية</option></select></label><label>نوع الشحن<select name="mode"><option>جوي</option><option>بحري</option></select></label><label>التصنيف<input name="category" list="category-options" required maxlength="80" placeholder="عام، عادية…"></label><label>الوحدة<select name="unit"><option>كجم</option><option>متر مكعب</option></select></label><label>العملة<select name="currency">${['USD','LYD','CNY','AED','SAR'].map(c=>option(c,c,'USD')).join('')}</select></label><label>السعر للوحدة<input name="rate" type="number" step="0.0001" min="0.0001" max="1000000" required></label></div><p class="muted">حفظ سعر لنفس الدولة والنوع والتصنيف يستبدل السعر القادم فقط؛ الفواتير السابقة لا تتغير.</p><button class="primary">حفظ السعر المعتمد</button><p role="status"></p></form></details>`}<div class="ops-panel"><div class="ops-grid">${customer?'':`<label>الزبون<select id="billing-customer">${customers.map(u=>option(u.code,`${u.code} · ${u.name}`,billingCustomer)).join('')}</select></label><label>شحنات رحلة محددة<select id="billing-trip">${option('','كل الرحلات',billingTrip)}${get().trips.map(t=>option(tripKey(t),`${t.code} · ${t.country} · ${t.mode}`,billingTrip)).join('')}</select></label><button id="invoice-new" class="primary">إصدار فاتورة للشحنات غير المفوترة</button>`}</div><div id="statement"></div></div>`;
 $('billing-refresh').onclick=renderBilling;if(!customer){$('billing-customer').onchange=()=>{billingCustomer=$('billing-customer').value;renderStatement()};$('billing-trip').onchange=()=>billingTrip=$('billing-trip').value;$('invoice-new').onclick=openInvoice;
 $('rates-list').innerHTML=billingData.rates.length?`<div class="table-wrap"><table><thead><tr><th>الدولة</th><th>نوع الشحن</th><th>التصنيف</th><th>السعر</th></tr></thead><tbody>${billingData.rates.map(r=>`<tr><td>${e(r.country)}</td><td>${e(r.mode)}</td><td>${e(r.category)}</td><td>${e(money(r.rate,r.currency))} / ${e(r.unit)}</td></tr>`).join('')}</tbody></table></div><br>`:'<p class="ops-warning">أضف أسعار الشركة المعتمدة قبل إصدار الفواتير.</p>';
 $('rate-form').elements.mode.onchange=ev=>$('rate-form').elements.unit.value=ev.target.value==='جوي'?'كجم':'متر مكعب';$('rate-form').onsubmit=async ev=>{ev.preventDefault();const f=ev.target,b=f.querySelector('button');b.disabled=true;try{await app.api('/billing/rates','POST',Object.fromEntries(new FormData(f)));await renderBilling();app.notice('تم حفظ السعر المعتمد.')}catch(err){f.querySelector('[role=status]').textContent=err.message;b.disabled=false}};
 }renderStatement();
 }catch(err){root.innerHTML=`<h2>الحسابات المالية</h2><p class="ops-error" role="status">${e(err.message)}</p><button id="billing-retry">إعادة المحاولة</button>`;$('billing-retry').onclick=renderBilling;}
}
function renderStatement(){
 const invoices=billingData.invoices.filter(i=>i.customer_code===billingCustomer),totals=new Map();invoices.forEach(i=>{const paid=billingData.payments.filter(p=>p.invoice_id===i.id).reduce((n,p)=>n+Number(p.amount),0),c=i.settlement_currency;totals.set(c,(totals.get(c)||0)+Number(i.settlement_total)-paid)});
 $('statement').innerHTML=`<h3>كشف حساب <span dir="ltr">${e(billingCustomer)}</span></h3><div class="status-strip">${[...totals].map(([c,v])=>`<span>المتبقي: <b>${e(money(v,c))}</b></span>`).join('')}</div>${invoices.length?invoices.map(i=>{const paid=billingData.payments.filter(p=>p.invoice_id===i.id).reduce((n,p)=>n+Number(p.amount),0);return `<article class="receipt"><div class="row"><h3>فاتورة SB-${String(i.number).padStart(6,'0')}</h3><span>${e(new Date(i.created_at).toLocaleDateString('ar-LY'))}</span></div><p>${num(i.lines.length)} شحنة · الإجمالي ${e(money(i.settlement_total,i.settlement_currency))} · المدفوع ${e(money(paid,i.settlement_currency))} · المتبقي ${e(money(Number(i.settlement_total)-paid,i.settlement_currency))}</p><div class="ops-actions"><button data-invoice="${e(i.id)}">عرض / طباعة الفاتورة</button>${get().user.role!=='customer'&&Number(i.settlement_total)-paid>0?`<button data-payment="${e(i.id)}">تسجيل دفعة</button>`:''}</div></article>`}).join(''):'<p>لا توجد فواتير محفوظة لهذا الحساب.</p>'}`;
 $('statement').querySelectorAll('[data-invoice]').forEach(b=>b.onclick=()=>showInvoice(b.dataset.invoice));$('statement').querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>openPayment(b.dataset.payment));
}
function openInvoice(){
 const billed=new Set(billingData.billed),rows=get().shipments.filter(s=>s.customer===billingCustomer&&!billed.has(s.id)&&(!billingTrip||tripKey(s)===billingTrip));if(!rows.length){app.notice('لا توجد شحنات غير مفوترة لهذا الاختيار.');return;}
 const d=$('detail');d.classList.add('ops-wide');d.innerHTML=`<form class="live-form" id="invoice-form"><div class="row"><h2>مراجعة فاتورة جديدة</h2><button type="button" id="invoice-close">إلغاء</button></div><p>الزبون <span dir="ltr">${e(billingCustomer)}</span> · ${num(rows.length)} شحنة. أزل تحديد الشحنات التي لا تريد فوترتها.</p><div class="table-wrap"><table><thead><tr><th>اختيار</th><th>الشحنة</th><th>التصنيف</th><th>الكمية</th><th>سعر الوحدة المعتمد</th></tr></thead><tbody>${rows.map(s=>{const r=billingData.rates.find(r=>r.country===s.country&&r.mode===s.mode&&r.category===s.category&&r.unit===s.unit);return `<tr><td><input type="checkbox" name="shipment" value="${e(s.id)}" ${r?'checked':''} ${r?'':'disabled'} aria-label="فوترة ${e(s.id)}"></td><td dir="ltr">${e(s.id)}</td><td>${e(s.category||'عام')}</td><td>${e(s.weight)}</td><td>${r?e(money(r.rate,r.currency)):'أضف السعر أولًا'}</td></tr>`}).join('')}</tbody></table></div><div class="ops-grid"><label>عملة أسعار الشحن<select name="currency">${['USD','LYD','CNY','AED','SAR'].map(c=>option(c,c,'USD')).join('')}</select></label><label>عملة السداد<select name="settlementCurrency">${['USD','LYD','CNY','AED','SAR'].map(c=>option(c,c,'USD')).join('')}</select></label><label>سعر التحويل (عملة السداد لكل 1 من عملة السعر)<input name="exchangeRate" type="number" required min="0.000001" max="1000000" step="0.000001" value="1"></label></div><p id="invoice-estimate" class="ops-note"></p><label class="ops-check"><input type="checkbox" name="confirmed" required>راجعت الشحنات والأسعار وسعر الصرف. يُثبّت المبلغ عند الإصدار.</label><p role="status"></p><button class="primary">إصدار الفاتورة</button></form>`;
 const f=$('invoice-form'),requestId=crypto.randomUUID();const calc=()=>{const checked=[...f.querySelectorAll('[name=shipment]:checked')].map(c=>rows.find(s=>s.id===c.value)),currency=f.elements.currency.value,settlement=f.elements.settlementCurrency.value;if(currency===settlement)f.elements.exchangeRate.value='1';f.elements.exchangeRate.readOnly=currency===settlement;let total=0;let error='';checked.forEach(s=>{const r=billingData.rates.find(r=>r.country===s.country&&r.mode===s.mode&&r.category===s.category&&r.unit===s.unit);if(r?.currency!==currency)error='كل الشحنات المحددة يجب أن تكون بنفس عملة السعر.';else total+=Math.round(s.weightValue*Number(r.rate)*100)/100});$('invoice-estimate').textContent=error||`إجمالي تقريبي للمراجعة: ${money(total,currency)} → ${money(total*Number(f.elements.exchangeRate.value),settlement)}. السعر النهائي يُحسب من الأسعار المحفوظة عند الإصدار.`;f.querySelector('.primary').disabled=!!error||!checked.length};
 f.onchange=calc;calc();$('invoice-close').onclick=()=>d.close();f.onsubmit=async ev=>{ev.preventDefault();const b=f.querySelector('.primary');b.disabled=true;try{const data=Object.fromEntries(new FormData(f));data.ids=[...f.querySelectorAll('[name=shipment]:checked')].map(c=>{const s=rows.find(s=>s.id===c.value),r=billingData.rates.find(r=>r.country===s.country&&r.mode===s.mode&&r.category===s.category&&r.unit===s.unit);return {id:s.id,updatedAt:s.updatedAt,rateUpdatedAt:r.updated_at}});await app.api('/billing/invoices','POST',{...data,customer:billingCustomer,requestId});d.close();await renderBilling();app.notice('تم إصدار الفاتورة وتثبيت الأسعار وسعر الصرف.')}catch(err){f.querySelector('[role=status]').textContent=err.message;b.disabled=false}};d.addEventListener('close',()=>d.classList.remove('ops-wide'),{once:true});d.showModal();
}
function showInvoice(id){const i=billingData.invoices.find(i=>i.id===id),payments=billingData.payments.filter(p=>p.invoice_id===id),d=$('detail');d.classList.add('ops-wide');d.innerHTML=`<div class="row"><h2>السلة الذكية · فاتورة SB-${String(i.number).padStart(6,'0')}</h2><button id="invoice-view-close">إغلاق</button></div><p>الزبون ${e(i.customer_code)} · ${e(new Date(i.created_at).toLocaleString('ar-LY'))}</p><div class="table-wrap"><table><thead><tr><th>الشحنة</th><th>الرحلة</th><th>التصنيف</th><th>الكمية</th><th>السعر</th><th>المجموع</th></tr></thead><tbody>${i.lines.map(l=>`<tr><td dir="ltr">${e(l.id)}</td><td>${e(l.trip)}</td><td>${e(l.category)}</td><td>${num(l.quantity)} ${e(l.unit)}</td><td>${e(money(l.rate,i.currency))}</td><td>${e(money(l.amount,i.currency))}</td></tr>`).join('')}</tbody></table></div><p>الإجمالي: ${e(money(i.total,i.currency))}<br>سعر التحويل المثبت: ${num(i.exchange_rate)}<br>المطلوب للسداد: ${e(money(i.settlement_total,i.settlement_currency))}</p><h3>الدفعات</h3>${payments.map(p=>`<p>${e(new Date(p.created_at).toLocaleDateString('ar-LY'))} · ${e(money(p.amount,i.settlement_currency))} · ${e(p.note)}</p>`).join('')||'<p>لا توجد دفعات مسجلة.</p>'}<button id="invoice-print" class="primary">طباعة / حفظ PDF</button>`;d.querySelector('#invoice-view-close').onclick=()=>d.close();d.querySelector('#invoice-print').onclick=()=>window.print();d.addEventListener('close',()=>d.classList.remove('ops-wide'),{once:true});d.showModal();}
function openPayment(id){const i=billingData.invoices.find(i=>i.id===id),paid=billingData.payments.filter(p=>p.invoice_id===id).reduce((n,p)=>n+Number(p.amount),0),remaining=Math.round((Number(i.settlement_total)-paid)*100)/100,d=$('detail'),requestId=crypto.randomUUID();d.innerHTML=`<form class="live-form"><h2>تسجيل دفعة · SB-${String(i.number).padStart(6,'0')}</h2><p>المتبقي ${e(money(remaining,i.settlement_currency))}</p><label>المبلغ المستلم بالفعل (${e(i.settlement_currency)})<input name="amount" type="number" required min="0.01" max="${remaining}" step="0.01"></label><label>ملاحظة / مرجع الإيصال<input name="note" maxlength="250"></label><p role="status"></p><button class="primary">حفظ الدفعة</button><button type="button" id="payment-close">إلغاء</button></form>`;d.querySelector('#payment-close').onclick=()=>d.close();d.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const f=ev.target,b=f.querySelector('.primary');b.disabled=true;try{await app.api('/billing/payments','POST',{...Object.fromEntries(new FormData(f)),invoice:id,id:requestId});d.close();await renderBilling();app.notice('تم تسجيل الدفعة.')}catch(err){f.querySelector('[role=status]').textContent=err.message;b.disabled=false}};d.showModal();}
let auditBefore=null,auditEntity='';
async function renderAudit(append=false){
 if(!append){auditBefore=null;$('audit').innerHTML=`<div class="ops-heading"><div><h2>سجل التغييرات</h2><p class="muted">يسجل التغييرات من تاريخ تفعيل هذه الإضافة، وليس التعديلات السابقة.</p></div></div><form id="audit-search" class="filters"><input name="entity" aria-label="رقم شحنة أو كود في السجل" placeholder="رقم الشحنة أو الكود" value="${e(auditEntity)}"><button>بحث في السجل</button></form><div id="audit-results"></div><p id="audit-error" role="status"></p><button id="audit-more" hidden>عرض الأقدم</button>`;$('audit-search').onsubmit=ev=>{ev.preventDefault();auditEntity=ev.target.elements.entity.value.trim();renderAudit()};$('audit-more').onclick=()=>renderAudit(true)}
 try{const rows=await app.api('/audit'+(auditBefore||auditEntity?'?'+new URLSearchParams({...auditBefore?{before:auditBefore}:{},...auditEntity?{entity:auditEntity}:{}}):''));const fields={customer_code:'الزبون',trip:'الرحلة',weight:'الوزن',unit:'الوحدة',step:'الحالة',country:'الدولة',mode:'نوع الشحن',category:'التصنيف',ship_date:'موعد الوصول',arrival_date:'موعد الرحلة',role:'الصلاحية',active:'تفعيل الحساب',rate:'السعر',currency:'العملة',whatsapp_opt_in:'موافقة واتساب',phone:'الهاتف',name:'الاسم',amount:'المبلغ'};
 const entities={sb_shipments:'شحنة',sb_trips:'رحلة',sb_accounts:'حساب',sb_rates:'سعر',sb_invoices:'فاتورة',sb_payments:'دفعة'},actions={INSERT:'إضافة',UPDATE:'تعديل',DELETE:'حذف'};
 $('audit-results').insertAdjacentHTML('beforeend',rows.map(a=>{const before=a.before_data||{},after=a.after_data||{},changed=Object.keys(fields).filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k]));return `<article class="receipt"><div class="row"><b>${e(actions[a.action]||a.action)} ${e(entities[a.entity]||a.entity)} · <span dir="ltr">${e(a.entity_id)}</span></b><small>${e(new Date(a.created_at).toLocaleString('ar-LY'))}</small></div><p>بواسطة <span dir="ltr">${e(a.actor)}</span>${a.batch_id?` · دفعة <span dir="ltr">${e(a.batch_id)}</span>`:''}</p>${changed.map(k=>`<p>${e(fields[k])}: <del>${e(k==='step'?stages[before[k]]||'—':before[k]??'—')}</del> ← <b>${e(k==='step'?stages[after[k]]||'—':after[k]??'—')}</b></p>`).join('')||'<p class="muted">تم حفظ العملية. لا تُعرض كلمات المرور أو مفاتيح الصور في السجل.</p>'}</article>`}).join('')||(!append?'<article>لا توجد تغييرات مطابقة.</article>':''));auditBefore=rows.at(-1)?.id;$('audit-more').hidden=rows.length<100;$('audit-error').textContent='';}catch(err){$('audit-error').textContent=err.message;}
}
let zxingPromise=null;
function loadZXing(){if(window.ZXingBrowser)return Promise.resolve(window.ZXingBrowser);if(!zxingPromise)zxingPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/vendor/zxing-browser.min.js';s.onload=()=>resolve(window.ZXingBrowser);s.onerror=()=>{zxingPromise=null;s.remove();reject(Error('تعذّر تحميل قارئ الباركود. استخدم الإدخال اليدوي.'))};document.head.append(s)});return zxingPromise;}
async function openScanner(reconcile=false){
 const d=$('detail'),t=reconcile?currentTrip():null;let controls=null,closed=false,cameraStarting=false;
 const stop=()=>{controls?.stop();controls=null;d.querySelector('video')?.srcObject?.getTracks().forEach(track=>track.stop())};
 d.innerHTML=`<div class="row"><h2>${reconcile?'مطابقة تفريغ الرحلة '+e(t.code):'مسح باركود الشحنة'}</h2><button id="scanner-close">إغلاق</button></div><p class="muted">${reconcile?'المسح لا يغيّر حالة الشحنة. القائمة مؤقتة حتى تحفظ تقرير المطابقة.':'امسح باركود رقم التتبع أو أدخله يدويًا.'}</p><video class="scan-video" id="scanner-video" muted playsinline></video><div class="review-actions"><button id="scanner-start">تشغيل الكاميرا</button><button id="scanner-stop">إيقاف الكاميرا</button><label class="photo-upload">قراءة باركود من صورة<input id="barcode-photo" type="file" accept="image/*" capture="environment"></label></div><form id="scanner-manual" class="filters"><input name="tracking" aria-label="رقم التتبع الممسوح" dir="ltr" required placeholder="رقم التتبع"><button>إدخال</button></form><p id="scanner-result" role="status"></p>${reconcile?'<div id="scanner-summary"></div><div class="review-actions"><button id="scan-save" class="primary">حفظ تقرير المطابقة</button><button id="scan-export">تنزيل تقرير CSV</button><button id="scan-reset">مسح قائمة العمل</button></div>':''}`;
 const rows=reconcile?currentRows():get().shipments,matched=()=>rows.filter(r=>scanSeen.has(r.id)),missing=()=>rows.filter(r=>!scanSeen.has(r.id)),extras=()=>[...scanSeen].filter(id=>!rows.some(r=>r.id===id));
 const update=()=>{if(reconcile)$('scanner-summary').innerHTML=`<p class="ops-note">مطابق: ${num(matched().length)} / ${num(rows.length)} · غير ممسوح: ${num(missing().length)} · خارج الكشف: ${num(extras().length)}</p><details><summary>الأرقام غير الممسوحة</summary><p dir="ltr">${missing().map(r=>e(r.id)).join('<br>')||'—'}</p></details><details><summary>أرقام خارج كشف الرحلة</summary><p dir="ltr">${extras().map(e).join('<br>')||'—'}</p></details>`};
 const accept=value=>{if(closed)return;const id=code(value);if(!/^[A-Z0-9-]{2,64}$/.test(id)){$('scanner-result').textContent='الباركود ليس رقم تتبع صالحًا.';return;}if(reconcile){if(scanSeen.has(id)){$('scanner-result').textContent=`${id} ممسوح سابقًا؛ لم يُحتسب مرتين.`;return;}scanSeen.add(id);$('scanner-result').textContent=rows.some(r=>r.id===id)?`${id} مطابق للرحلة`:`${id} خارج كشف هذه الرحلة`;update();}else{stop();d.close();app.tab('ship');['filter-trip','filter-country','filter-mode','filter-step'].forEach(k=>$(k).value='');$('search').value=id;app.renderShipments();app.notice(get().shipments.some(r=>r.id===id)?'تم العثور على الشحنة.':'رقم التتبع غير موجود في شحناتك المتاحة.')}};
 $('scanner-close').onclick=()=>d.close();$('scanner-stop').onclick=()=>{stop();$('scanner-result').textContent='تم إيقاف الكاميرا.'};d.addEventListener('close',()=>{closed=true;stop()},{once:true});const onVisibility=()=>{if(document.hidden)stop()};document.addEventListener('visibilitychange',onVisibility);d.addEventListener('close',()=>document.removeEventListener('visibilitychange',onVisibility),{once:true});
 $('scanner-manual').onsubmit=ev=>{ev.preventDefault();accept(ev.target.elements.tracking.value);ev.target.reset()};
 $('scanner-start').onclick=async()=>{if(cameraStarting)return;cameraStarting=true;stop();$('scanner-start').disabled=true;try{if(!navigator.mediaDevices?.getUserMedia)throw Error('الكاميرا غير متاحة هنا. استخدم صورة أو قارئ باركود خارجي.');const Z=await loadZXing();if(closed)return;const reader=new Z.BrowserMultiFormatReader();controls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'}}},$('scanner-video'),result=>{if(result)accept(result.getText())});if(closed)stop();else $('scanner-result').textContent='وجّه الكاميرا نحو الباركود.';}catch(err){if(!closed)$('scanner-result').textContent=err.name==='NotAllowedError'?'لم تسمح بالوصول إلى الكاميرا. استخدم صورة أو الإدخال اليدوي.':err.message;}finally{cameraStarting=false;if(!closed)$('scanner-start').disabled=false}};
 $('barcode-photo').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;if(file.size>10*1024*1024){$('scanner-result').textContent='اختر صورة أقل من 10 ميجابايت.';return;}const url=URL.createObjectURL(file);try{const Z=await loadZXing();const result=await new Z.BrowserMultiFormatReader().decodeFromImageUrl(url);accept(result.getText())}catch{if(!closed)$('scanner-result').textContent='لم نستطع قراءة الباركود. جرّب صورة أوضح أو أدخل الرقم يدويًا.'}finally{URL.revokeObjectURL(url);ev.target.value=''}};
 if(reconcile){$('scan-export').onclick=()=>download(`reconciliation-${t.code}.csv`,csv([['رقم التتبع','نتيجة المسح'],...rows.map(r=>[r.id,scanSeen.has(r.id)?'مطابق':'غير ممسوح']),...extras().map(id=>[id,'خارج الكشف'])]));$('scan-reset').onclick=()=>{if(window.confirm('مسح قائمة الباركود المؤقتة لهذه الرحلة؟')){scanSeen.clear();update()}};$('scan-save').onclick=async()=>{const b=$('scan-save');if(!scanSeen.size){$('scanner-result').textContent='امسح شحنة واحدة على الأقل قبل حفظ التقرير.';return;}b.disabled=true;stop();try{await app.api('/reconciliations','POST',{trip:t.code,country:t.country,mode:t.mode,scanned:[...scanSeen]});d.close();await loadReconciliations(t);app.notice('تم حفظ تقرير المطابقة. لم تتغير حالات الشحنات.')}catch(err){$('scanner-result').textContent=err.message;b.disabled=false}};update();}d.showModal();
}
async function loadReconciliations(t){const key=tripKey(t);try{const reports=await app.api('/reconciliations?'+new URLSearchParams({trip:t.code,country:t.country,mode:t.mode}));if(key!==selectedTrip||!$('reconcile-summary'))return;$('reconcile-summary').innerHTML=reports.length?'<h3>تقارير المطابقة المحفوظة</h3>'+reports.map(r=>{const scanned=new Set(r.scanned_ids),expected=new Set(r.expected_ids),missing=r.expected_ids.filter(id=>!scanned.has(id)),extra=r.scanned_ids.filter(id=>!expected.has(id));return `<details class="ops-panel"><summary>${e(new Date(r.created_at).toLocaleString('ar-LY'))} · ${e(r.created_by)} · ${num(expected.size-missing.length)} مطابق، ${num(missing.length)} غير ممسوح، ${num(extra.length)} خارج الكشف</summary><p>غير ممسوح: <span dir="ltr">${missing.map(e).join(', ')||'—'}</span></p><p>خارج الكشف: <span dir="ltr">${extra.map(e).join(', ')||'—'}</span></p></details>`}).join(''):'';}catch(err){if(key===selectedTrip&&$('reconcile-summary'))$('reconcile-summary').innerHTML=`<p class="muted">تعذّر تحميل تقارير المطابقة: ${e(err.message)}</p>`}}
