import test from 'node:test';import assert from 'node:assert/strict';import worker from '../_worker.js';
const env={SUPABASE_URL:'https://database.test',SUPABASE_SERVICE_ROLE_KEY:'TEST-ONLY',ASSETS:{fetch:async()=>new Response('asset')}};
let role='admin',calls=[];const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,opts={})=>{const u=new URL(url);assert.equal(u.origin,'https://database.test');calls.push({path:u.pathname+u.search,method:opts.method,body:opts.body&&JSON.parse(opts.body),headers:opts.headers});let value=[];
 if(u.pathname.endsWith('/sb_sessions'))value=[{account_code:'TEST-USER',account_salt:'salt'}];
 else if(u.pathname.endsWith('/sb_accounts'))value=[{code:'TEST-USER',name:'Test',active:true,role,salt:'salt',password_hash:'SECRET',phone:'+218900000000'}];
 else if(u.pathname.endsWith('/sb_shipments'))value=[{id:'TRACK-1',customer_code:'OTHER-USER',country:'الصين',mode:'جوي',weight:1,unit:'كجم',trip:'110',step:0,ship_date:'2026-09-23',photo_key:null,updated_at:'2026-09-11T20:00:00Z'}];
 else if(u.pathname.endsWith('/sb_operations_batch'))value={created:1,updated:0,batchId:'TEST'};
 return Response.json(value);
};
const req=(path,method='GET',data,origin='https://app.test')=>new Request('https://app.test'+path,{method,headers:{Cookie:'salla_session='+'a'.repeat(64),Origin:origin,'Content-Type':'application/json'},body:method==='GET'?undefined:JSON.stringify(data||{})});
const run=async(r,newRole='admin')=>{role=newRole;calls=[];return worker.fetch(r,env)};
test('CSRF: cross-origin write rejected before database access',async()=>{const r=await run(req('/api/shipments/import','POST',{},'https://evil.test'));assert.equal(r.status,403);assert.equal(calls.length,0)});
test('unauthenticated read rejected',async()=>{const r=await run(new Request('https://app.test/api/state'));assert.equal(r.status,401)});
test('customer cannot view another shipment image',async()=>assert.equal((await run(req('/api/shipments/TRACK-1/photo'),'customer')).status,404));
test('customer cannot import or read audit',async()=>{assert.equal((await run(req('/api/shipments/import','POST',{}),'customer')).status,403);assert.equal((await run(req('/api/audit'),'customer')).status,403)});
test('warehouse cannot delete shipments or change rates',async()=>{assert.equal((await run(req('/api/shipments/TRACK-1','DELETE',{}),'warehouse')).status,403);assert.equal((await run(req('/api/billing/rates','POST',{}),'warehouse')).status,403)});
test('accountant cannot edit shipments; staff cannot read money',async()=>{assert.equal((await run(req('/api/shipments/TRACK-1','PATCH',{step:1}),'accountant')).status,403);assert.equal((await run(req('/api/billing'),'staff')).status,403)});
test('customer billing reads are scoped server-side',async()=>{const r=await run(req('/api/billing'),'customer');assert.equal(r.status,200);assert.ok(calls.find(c=>c.path.includes('sb_invoices?')).path.includes('customer_code=eq.TEST-USER'));assert.ok(calls.find(c=>c.path.includes('sb_payments?')).path.includes('sb_invoices.customer_code=eq.TEST-USER'));assert.ok(!calls.some(c=>c.path.includes('sb_rates')))});
test('invalid and duplicate import rows rejected before transaction',async()=>{const b={trip:'110',country:'الصين',mode:'جوي',rows:[{id:'A100',customer:'LN-',weight:1,unit:'كجم',action:'create'}]};assert.equal((await run(req('/api/shipments/import','POST',b))).status,400);b.rows[0].customer='LN-0144';b.rows.push(b.rows[0]);assert.equal((await run(req('/api/shipments/import','POST',b))).status,400);assert.ok(!calls.some(c=>c.path.includes('sb_operations_batch')))});
test('validated import uses single transaction and authenticated actor',async()=>{const r=await run(req('/api/shipments/import','POST',{trip:'110',country:'الصين',mode:'جوي',rows:[{id:'A100',customer:'LN-0144',weight:1,unit:'كجم',action:'create'}]}));assert.equal(r.status,200);const writes=calls.filter(c=>c.method==='POST');assert.equal(writes.length,1);assert.equal(writes[0].headers['x-sb-actor'],'TEST-USER');assert.equal(writes[0].headers['x-sb-whatsapp'],'disabled')});
test('consent changes only the authenticated customer',async()=>{assert.equal((await run(req('/api/notifications/consent','POST',{enabled:true,code:'OTHER'}),'customer')).status,200);assert.ok(calls.find(c=>c.method==='PATCH').path.endsWith('code=eq.TEST-USER'))});
test('SQL, setup documents, and dispatcher code are not public assets',async()=>{for(const p of ['/db/operations.sql','/whatsapp/worker.mjs','/tests/database-rollback.sql'])assert.equal((await run(req(p))).status,404)});
test('app ships self-hosted parser and scanner assets',async()=>{for(const p of ['/operations.mjs','/vendor/xlsx.full.min.js','/vendor/zxing-browser.min.js'])assert.equal((await run(req(p))).status,200)});
test.after(()=>{globalThis.fetch=originalFetch});
